INSERT INTO GENRE (GENRE_ID, GENRE) VALUES (1, 'rap');
INSERT INTO GENRE (GENRE_ID, GENRE) VALUES (2, 'rock´n roll');
INSERT INTO GENRE (GENRE_ID, GENRE) VALUES (3, 'pop');

INSERT INTO TRACK VALUES (1, 'some artist1', 'path/to/sample1', 'title1');
INSERT INTO TRACK VALUES (2, 'some artist2', 'path/to/sample2', 'title2');
INSERT INTO TRACK VALUES (3, 'some artist3', 'path/to/sample3', 'title3');
INSERT INTO TRACK VALUES (4, 'some artist4', 'path/to/sample4', 'title4');
INSERT INTO TRACK VALUES (5, 'some artist5', 'path/to/sample5', 'title5');

INSERT INTO TRACK_GENRES VALUES (1, 1);
INSERT INTO TRACK_GENRES VALUES (1, 2);
INSERT INTO TRACK_GENRES VALUES (1, 3);
INSERT INTO TRACK_GENRES VALUES (2, 1);
INSERT INTO TRACK_GENRES VALUES (3, 2);
INSERT INTO TRACK_GENRES VALUES (4, 2);
INSERT INTO TRACK_GENRES VALUES (4, 2);
INSERT INTO TRACK_GENRES VALUES (4, 3);


